apiVersion: v1
kind: Pod
metadata:
  name: first-pod
  labels:
    app: first-pod
spec:
  containers:
    - name: app
      image: busybox:1.36
      command:
        - sh
        - -c
        - |
          while true; do
            echo "The first Pod is working."
            sleep 10
          done
