apiVersion: v1
kind: Pod
metadata:
  name: primeiro-pod
  labels:
    app: primeiro-pod
spec:
  containers:
    - name: aplicacao
      image: busybox:1.36
      command:
        - sh
        - -c
        - |
          while true; do
            echo "O primeiro Pod esta funcionando."
            sleep 10
          done

