apiVersion: apps/v1
kind: Deployment
metadata:
  name: exemplo-web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: exemplo-web
  template:
    metadata:
      labels:
        app: exemplo-web
    spec:
      containers:
        - name: web
          image: nginx:1.27-alpine
          ports:
            - containerPort: 80

